import "./globals.css";
import type { Metadata } from "next";
import { Noto_Sans_JP, Zen_Kaku_Gothic_New, Open_Sans } from "next/font/google";
import Header from "./_components/Header";
import Footer from "./_components/Footer";

const NotoSansJPFont = Noto_Sans_JP({
  subsets: ["latin"],
  display: "swap",
});

const ZenKakuGothicNewFont = Zen_Kaku_Gothic_New({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
  display: "swap",
});

const OpenSansFont = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "中部流通株式会社 採用サイト",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ja"
      className={`
      ${NotoSansJPFont.className}
      ${ZenKakuGothicNewFont.className}
      ${OpenSansFont.className}
      `}
    >
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
